name: GitHub Actions - Create Release

on:
  pull_request_review:
    types:
      - submitted

jobs:
  CreateRelease:
    name: Create release for github-actions package
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref == 'release/actions' && github.event.review.state == 'approved' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        uses: actions/github-script@v6
        with:
          script: |
            const script = require( './.github/scripts/github-actions-create-release.js' );
            await script( {
              github,
              context,
              workspace: '${{ github.workspace }}',
              outputJsonPath: '/tmp/release.json',
            } );

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: /tmp/release.json
